server:
  port: 10087

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10086/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        # 提前加载配置文件，保证后续数据库连接正常启动
        bootstrap: true
        default-profile: default
        default-label: master
        git:
          uri: https://gitee.com/dugfa/urban-trajectory-visualization-system-config
          username: duguangfa@outlook.com
          password: ztdz9TVgiVPD5LM

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
